<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="generator" content="HTML Tidy for Linux/x86 (vers 1 September 2005), see www.w3.org" />
<title>Creative Commons Legal Code</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="https://creativecommons.org/includes/deed3.css" media="screen" />
<link rel="stylesheet" type="text/css" href="https://creativecommons.org/includes/deed3-print.css" media="print" />
<!--[if lt IE 7]><link rel="stylesheet" type="text/css" href="https://creativecommons.org/includes/deed3-ie.css" media="screen" /><![endif]-->
<script type="text/javascript" src="https://creativecommons.org/includes/errata.js">
</script>
</head>
<body>
<p align="center" id="header"><a href="https://creativecommons.org/">Creative Commons</a></p>
<div id="deed" class="green">
<div id="deed-head">
<div id="cc-logo">
<img src="https://creativecommons.org/images/deed/cc-logo.jpg" alt="" />
</div>
<h1><span>Creative Commons Legal Code</span></h1>
<div id="deed-license">
<h2>Attribution-ShareAlike 3.0 Unported</h2>
</div>
</div>
<div id="deed-main">
